Linear Algebra(vectors&metrices)

In [1]:
import numpy as np

v = np.array([1, 2, 3])

A = np.array([[1, 2, 3],
              [4, 5, 6]])

print("Vector:", v)
print("Matrix:\n", A)

Vector: [1 2 3]
Matrix:
 [[1 2 3]
 [4 5 6]]


Matrix Addition & Scalar Multiplication

In [2]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print("Addition:\n", A + B)
print("Scalar Multiplication:\n", 2 * A)

Addition:
 [[ 6  8]
 [10 12]]
Scalar Multiplication:
 [[2 4]
 [6 8]]


Matrix Multiplication

In [3]:
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

# Method 1
C = np.dot(A, B)

# Method 2 (recommended)
C2 = A @ B

print("Matrix Multiplication:\n", C2)

Matrix Multiplication:
 [[19 22]
 [43 50]]


Transpose of Matrix

In [4]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])

print("Transpose:\n", A.T)

Transpose:
 [[1 4]
 [2 5]
 [3 6]]


Determinant

In [5]:
A = np.array([[1, 2],
              [3, 4]])

det = np.linalg.det(A)
print("Determinant:", det)

Determinant: -2.0000000000000004


Inverse of Matrix

In [6]:
A = np.array([[1, 2],
              [3, 4]])

inv = np.linalg.inv(A)
print("Inverse:\n", inv)

Inverse:
 [[-2.   1. ]
 [ 1.5 -0.5]]


Eigenvalues & Eigenvectors

In [7]:
A = np.array([[2, 0],
              [0, 3]])

values, vectors = np.linalg.eig(A)

print("Eigenvalues:", values)
print("Eigenvectors:\n", vectors)

Eigenvalues: [2. 3.]
Eigenvectors:
 [[1. 0.]
 [0. 1.]]


Solving Linear Equations

In [8]:
A = np.array([[2, 1],
              [1, 3]])

b = np.array([8, 13])

x = np.linalg.solve(A, b)

print("Solution x:", x)

Solution x: [2.2 3.6]


Rank of Matrix

In [9]:
A = np.array([[1, 2],
              [2, 4]])

rank = np.linalg.matrix_rank(A)
print("Rank:", rank)

Rank: 1


Norm (Vector Length)

In [10]:
v = np.array([3, 4])

norm = np.linalg.norm(v)
print("Norm:", norm)   # Should be 5

Norm: 5.0
