In [1]:
pip install numpy

In [2]:
import numpy as np


N-Dimensional Array

In [3]:
import numpy as np

arr = np.array([[1,2,3],
                [4,5,6]])

print(arr)

[[1 2 3]
 [4 5 6]]


Number of Dimensions

In [4]:
print(arr.ndim)

2


shapes


In [5]:
print(arr.shape)


(2, 3)


Data Type

In [6]:
print(arr.dtype)

int64


Size

In [7]:
print(arr.size)

6


Zeros

In [8]:
a = np.zeros((3,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


ones

In [9]:
b = np.ones((2,4))
print(b)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


Sequence

In [10]:
c = np.arange(0,10,2)
print(c)

[0 2 4 6 8]


Random Module

In [11]:
import numpy as np

arr = np.random.randint(1,10,(3,3))
print(arr)

[[6 1 5]
 [3 3 7]
 [5 4 3]]


Indexing

In [12]:
print(arr[0,1])

1


Slicing

In [13]:
print(arr[0:2,1:3])

[[1 5]
 [3 7]]


Array Operations

In [14]:
a = np.array([1,2,3])
b = np.array([4,5,6])

print(a+b)
print(a*b)

[5 7 9]
[ 4 10 18]


Broadcasting

In [15]:
a = np.array([[1,2,3],
              [4,5,6]])

b = np.array([10,20,30])

print(a + b)

[[11 22 33]
 [14 25 36]]


Trignometric Functions

In [16]:
import numpy as np

angles = np.array([0, np.pi/2, np.pi])

print(np.sin(angles))
print(np.cos(angles))
print(np.tan(angles))

[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[ 1.000000e+00  6.123234e-17 -1.000000e+00]
[ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


Statistical Functions

In [17]:
arr = np.array([10,20,30,40,50])

Mean

In [18]:
print(np.mean(arr))

30.0


Median

In [20]:
print(np.median(arr))

30.0


Standard Deviation

In [21]:
print(np.std(arr))

14.142135623730951


Variance

In [22]:
print(np.var(arr))

200.0


Min/Max

In [23]:
print(np.min(arr))
print(np.max(arr))

10
50


Sum

In [24]:
print(np.sum(arr))

150


Shape Manipulation
Reshape

In [25]:
arr = np.arange(1,7)

new_arr = arr.reshape(2,3)

print(new_arr)

[[1 2 3]
 [4 5 6]]


flatten

In [26]:
print(new_arr.flatten())

[1 2 3 4 5 6]


Ravel

In [27]:
print(new_arr.ravel())

[1 2 3 4 5 6]


Transpose

In [28]:
print(new_arr.T)

[[1 4]
 [2 5]
 [3 6]]


Joining Arrays

In [29]:
a = np.array([[1,2]])
b = np.array([[3,4]])

print(np.concatenate((a,b)))

[[1 2]
 [3 4]]


hstack

In [30]:
print(np.hstack((a,b)))

[[1 2 3 4]]


Splitting Arrays

In [31]:
arr = np.array([1,2,3,4,5,6])

print(np.split(arr,3))

[array([1, 2]), array([3, 4]), array([5, 6])]


Linear Algebra

In [32]:
A = np.array([[1,2],
              [3,4]])

B = np.array([[5,6],
              [7,8]])

Matrix Multiplication

In [33]:
print(np.dot(A,B))

[[19 22]
 [43 50]]


Inverse

In [34]:
print(np.linalg.inv(A))

[[-2.   1. ]
 [ 1.5 -0.5]]
